# Default values for rbac-manager.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: quay.io/reactiveops/rbac-manager
  tag: 0.3.0
  pullPolicy: Always

rbacdefinition:
  create: False
  content:
    rbacUsers:
      - user: somenewadmin
        kind: ServiceAccount
        clusterRoleBindings:
        - clusterRole: cluster-admin

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
