rbac-manager:
  enabled: True
  image:
    repository: quay.io/reactiveops/rbac-manager
    tag: 0.3.0
    pullPolicy: Always
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 128Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}

rbacdefinition:
  enabled: False
  content:
    rbacUsers:
      - user: somenewadmin
        kind: ServiceAccount
        clusterRoleBindings:
        - clusterRole: cluster-admin

