apiVersion: rbac-manager.reactiveops.io/v1beta1
kind: RbacBinding
metadata:
  name: example-group
spec:
  subjects:
    - kind: Group
      name: example
  clusterRoleBindings:
    - clusterRole: edit
  roleBindings:
    - clusterRole: admin
      namespace: default
---
apiVersion: rbac-manager.reactiveops.io/v1beta1
kind: RbacBinding
metadata:
  name: example-users
spec:
  subjects:
    - kind: User
      name: rob@example.com
    - kind: User
      name: joe@example.com
  clusterRoleBindings:
    - clusterRole: edit
  roleBindings:
    - clusterRole: admin
      namespace: default
---
apiVersion: rbac-manager.reactiveops.io/v1beta1
kind: RbacBinding
metadata:
  name: example-service-account
spec:
  subjects:
    - kind: ServiceAccount
      name: example
      namespace: default
  clusterRoleBindings:
    - clusterRole: view
  roleBindings:
    - clusterRole: admin
      namespace: default