{{ if .Values.rbacDefinition.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "rbac-manager.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
  labels:
    app: {{ template "rbac-manager.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  template:
    metadata:
      name: {{ template "rbac-manager.fullname" . }}
      labels:
        app: {{ template "rbac-manager.name" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ template "rbac-manager.fullname" . }}-job
      containers:
        - name: hyperkube
          image: "{{ .Values.global.hyperkube.repository }}:{{ .Values.global.hyperkube.tag }}"
          command:
            - ./kubectl
            - apply
            - -f
            - /tmp/rbac-definition/rbac-definition.yaml
          volumeMounts:
            - mountPath: "/tmp/rbac-definition"
              name: rbac-definition
      volumes:
        - name: rbac-definition
          configMap:
            name: {{ template "rbac-manager.fullname" . }}
      restartPolicy: Never
{{ end }}
