- user: one@example.com
  clusterRoleBindings:
    - clusterRole: admin
- user: two@example.com
  clusterRoleBindings:
    - clusterRole: edit
  roleBindings:
    - clusterRole: cluster-admin
      namespace: default
- user: three@example.com
  roleBindings:
    - clusterRole: edit
      namespace: default
    - role: custom
      namespace: nginx-ingress
    - role: custom2
      namespace: kube-lego
- user: four@example.com
  roleBindings:
    - clusterRole: admin
      namespace: default
    - role: custom2
      namespace: kube-lego
- user: five@example.com
  roleBindings:
    - clusterRole: admin
      namespace: default
    - role: custom4
      namespace: nginx-ingress
    - role: custom4
      namespace: kube-lego
    - role: custom5
      namespace: kube-lego
