apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: rbacdefinitions.rbac-manager.reactiveops.io
spec:
  group: rbac-manager.reactiveops.io
  names:
    kind: RbacDefinition
    listKind: RbacDefinitionList
    plural: rbacdefinitions
    singular: rbacdefinition
  scope: Namespaced
  version: v1beta1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rbac-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      name: rbac-manager
  resources:
    requests:
      cpu: 50m
      memory: 50Mi
  template:
    metadata:
      labels:
        name: rbac-manager
    spec:
      containers:
        - name: rbac-manager
          image: quay.io/robertjscott/rbac-manager:dev
          imagePullPolicy: Always
