---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rbac-manager
  namespace: rbac-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      run: rbac-manager
  template:
    metadata:
      labels:
        run: rbac-manager
    spec:
      serviceAccountName: rbac-manager
      containers:
        - name: rbac-manager
          image: quay.io/reactiveops/rbac-manager:latest

