---
kind: ConfigMap
apiVersion: v1
metadata:
  name: rbac-manager-config
  namespace: rbac-manager
data:
  rbac.yaml: |-
    - user: one@example.com
      clusterRoleBindings:
        - clusterRole: cluster-admin
    - user: two@example.com
      clusterRoleBindings:
        - clusterRole: edit
      roleBindings:
        - clusterRole: cluster-admin
          namespace: default
